### ISSUE TITLE
Test fails to compare list with list

### ISSUE THREAD

**Issue by gilfrade** [tailsdotcom/boolrule#1]
* boolrule version: 0.2
* Python version: 2.7.13
* Operating System: Fedora

### Description

I'm tying to validate a list of numbers but i'm not getting the test done properly.

### What I Did

Created a rule with "number_list.value in (15,20,25) and another_number = 10"
Tested values from 0 to 30 with { "number_list": [i, i+1], "another_number": 10 } but test fails
If i test values from 0 to 30 with { "number_list": i, "another_number": 10 } the test is done correctly

What can i do to compare a list with a list?

**Comment by gilfrade** [comment]
Sorry, my mistake. Was trying to test integer values with float values.

**Comment by spjwebster** [comment]
As present Boolrule is fairly basic in its comparisons, so there's no way to see if each number in a list is part of another list. 

Thinking in terms of what we'd need to add to boolrule to support this, we first need a way to express what kind of comparison you want for the list within the condition expression. From your example, I'd guess that you want to be able to express "are any numbers in `number_list` present in the given list of numbers", which maps quite nicely to python's `any()` builtin. For completeness, we'd also want "are all numbers in `number_list` in the given list of numbers", which maps to `all()`.

I'm thinking that being able to write expressions such as the below would meet your use case:

    any(number_list) in (15,20,25) and another_number=10

Would that give you what you're looking for?

**Comment by spjwebster** [comment]
@gilfrade any comment on the above proposal?

**Comment by gilfrade** [comment]
I used more or less you suggestion. I added the following new operators that suited my needs:
```python
if operator in ('=', '==', 'eq'):
                passed = lval == rval
            elif operator in ('!=', 'ne'):
                passed = lval != rval
            elif operator in ('>', 'gt'):
                passed = lval > rval
            elif operator in ('>=', 'ge'):
                passed = lval >= rval
            elif operator in ('<', 'lt'):
                passed = lval < rval
            elif operator in ('<=', 'le'):
                passed = lval <= rval
            elif operator == 'in':
                passed = not bool(sum(map(lambda x: x not in lval, rval)))
            elif operator == 'inany':
                passed = any((True for x in lval if x in rval))
            elif operator == 'notinany':
                passed = not bool(sum(map(lambda x: x in lval, rval)))
            elif operator == 'notin':
                passed = bool(sum(map(lambda x: x not in lval, rval)))
            else:
                raise UnknownOperatorException(
                    "Unknown operator '{}'".format(operator)
                )
```
notinany #at least one value does not exist
inany #at least one value exist
in #all values must exist 
notin #none of the values exist

And the rules created are like this:
"ts_pids_list.value in (256,257)"
checks against object {"ts_pids_list": [0, 34, 35, 256, 257]}

Thanks for your help.
