### ISSUE TITLE
Test fail when the expression contains boolean constant.

### ISSUE THREAD

**Issue by homholueng** [tailsdotcom/boolrule#2]
* boolrule version: 0.2.0
* Python version: 2.7.12
* Operating System: macOS 10.12.6

### Description

I try to evaluate a bool expression which contains bool constant (e.g. `'result == True'`, `'True == False'`) then I got an exception like that:

```python
    174
    175             operator = items['operator']
--> 176             lval = self._expand_val(items['lval'][0], context)
    177             rval = self._expand_val(items['rval'][0], context)
    178

KeyError: 0
```

### What I Did

```python
In [2]: BoolRule('True == False').test()

In [3]: result = {
   ...: 'result': True,
   ...: 'data': {
   ...:     'name': 'howell',
   ...:     'info': {
   ...:             'age': 21,
   ...:             'sex': 'male'
   ...: }}}

In [4]: BoolRule('result == True').test(result)
```

### More detail

I dive into the source code when this Exception was raised. I found an interesting thing:

```python
            lval = self._expand_val(items['lval'][0], context)
            rval = self._expand_val(items['rval'][0], context)
```

The code above assume the `item['lval']` and `item['rval']` can be access by index. But when I check the `items` which get from `token.asDict()` (token for `BoolRule('result == True')`), I got this:

```python
{'lval': [SubstituteVal(result)], 'operator': '==', 'rval': {'bool': True}}
```

So the `rval` is a `dict` instead of `list`.

**Comment by spjwebster** [comment]
Thank you for the bug report @homholueng. Can confirm this is an issue and will work on a fix shortly.

**Comment by spjwebster** [comment]
Fix in place. Will push a point release shortly.

**Comment by spjwebster** [comment]
@homholueng I've just pushed a patch release (v0.2.1) that fixes this issue. Thanks again for reporting.
